server:
  port: 8087

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: mall-search
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
  elasticsearch:
    uris: http://localhost:9200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.mall.search: debug